### ISSUE TITLE
please i need

### ISSUE THREAD

**Issue by imhajes** [M-Ahadi/site_visitor#1]
i need this script to work in ubuntu linux with one rotating proxy and i need chrome work headless

**Comment by M-Ahadi** [comment]
Hi @imhajes 

Sorry for late response. you can use dockerized version now.

**Comment by rickyandram** [comment]
bro is it working on windows ..???

**Comment by M-Ahadi** [comment]
@rickyandram 
you can download chromedriver for windows and put in the project directory. It should work.

https://chromedriver.chromium.org/downloads

**Comment by rickyandram** [comment]
C:\Users\Ramsaran\Desktop\site_visitor-1.1>main.py
Traceback (most recent call last):
  File "C:\Users\Ramsaran\Desktop\site_visitor-1.1\main.py", line 7, in <module>
    import configs
  File "C:\Users\Ramsaran\Desktop\site_visitor-1.1\configs.py", line 7, in <module>
    LOG_LEVEL = os.getenv("LOG_LEVEL").upper()
AttributeError: 'NoneType' object has no attribute 'upper'

**Comment by rickyandram** [comment]
i m getting error

**Comment by M-Ahadi** [comment]
@rickyandram 
bug fixed and it now supports windows

**Comment by rickyandram** [comment]
where i paste url

**Comment by M-Ahadi** [comment]
@rickyandram edit config.py file

**Comment by rickyandram** [comment]
URL = os.getenv("URL", google.com)
NameError: name 'google' is not defined

**Comment by M-Ahadi** [comment]
@rickyandram you should put url between quotations

**Comment by rickyandram** [comment]
ok it is working bro Thanks ..Allah bless you
